apiVersion: v1
kind: Namespace
metadata:
  name: http-test

---
apiVersion: v1
kind: Service
metadata:
  name: http-service
  labels:
    apps: http-test
  namespace: http-test
spec:
  type: ClusterIP
  selector:
    app: http-test
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-path
  namespace: http-server
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: http-pv 
  namespace: http-test 
spec: 
  capacity:
    storage: 2Gi 
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: local-path
  local: 
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: In 
            values:
              - ''
            
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: http-pvc
  namespace: http-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
  namespace: http-test
spec:
  selector:
    matchLabels:
      app: http-test
  replicas: 1
  template:
    metadata:
      labels:
        app: http-test
    spec:
      containers:
      - name: http-server
        image: "ghcr.io/backchristoffer/http-test:latest"
        ports:
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
        - name: http-vol
          mountPath: /data
      volumes:
      - name: http-vol
        persistentVolumeClaim:
          claimName: http-pvc